name = "portfolio"
main = "src/index.ts"
compatibility_date = "2026-02-23"
workers_dev = true

routes = [
  { pattern = "kiakiraki.dev", custom_domain = true },
  { pattern = "www.kiakiraki.dev", custom_domain = true }
]

[assets]
directory = "./public"
